---
variables:
  PROJECT_NAME: xoutil

stages:
  - test
  - check
  - build
  - publish
  - clean

run all tests:
  stage: test
  script: tox -e2.7-unit,3.5-unit,2.7-greenlets
  tags:
    - python
    - virtualenv
    - tox
  only:
    - branches

check signature of tag:
  stage: check
  script:
    - git verify-tag $CI_COMMIT_REF_NAME
  tags:
    - git
    - gpg
  only:
    - tags

build source distribution:
  stage: build
  script:
    - rm -f dist/*
    - python setup.py sdist
  tags:
    - python
  artifacts:
    paths:
      - dist/
  only:
    - tags

build binary distribution:
  stage: build
  script:
    - rm -f dist/*
    - python setup.py bdist_wheel
  tags:
    - wheel
  artifacts:
    paths:
      - dist/
  only:
    - tags

publish_locally:
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - ssh manu@gestion.lahavane.com "mkdir -p Repos/$PROJECT_NAME"
    - scp dist/* manu@gestion.lahavane.com:Repos/$PROJECT_NAME/
  tags:
    - repo.lahavane.com
  only:
    - tags
  dependencies:
    - check signature of tag
    - build source distribution
    - build binary distribution


publish_pypi:
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - twine upload dist/*
  tags:
    - twine
  only:
    - tags
  dependencies:
    - check signature of tag
    - build source distribution
    - build binary distribution
  environment:
    name: pypi
    url: https://pypi.python.org/pypi/$PROJECT_NAME


clean_build:
  variables:
    GIT_STRATEGY: none
  stage: clean
  script:
    - rm -f dist/*
  tags:
    - python
  when: always
  allow_failure: true
  dependencies:
    - build source distribution
    - build binary distribution
