---
stages:
  - test
  - check
  - build
  - publish

check code smells:
  image: python:3.6-alpine
  script:
    - pip install merchise.lint==0.11
    - merchise_lint3
  stage: pre-check
  allow_failure: true
  only:
    - master
    - merge_requests

.run_tox_tests: &run_tox_tests
  image: python:$PYTHON-alpine
  stage: test
  script:
    - pip install tox
    - tox -e system-unit,$PYTHON-greenlets


.run_tox_staticcheck: &run_tox_staticcheck
  image: python:3.6-alpine
  stage: pre-check
  cache:
    key: mypy-${CI_COMMIT_REF_SLUG}
    paths:
      - .tox/3.6-staticcheck/
      - .mypy_cache/
  script:
    - apk add g++
    - pip install tox
    - tox -e 3.6-staticcheck

run all Python 3.4 tests:
  <<: *run_tox_tests
  image: python:3.4
  variables:
    PYTHON: "3.4"


run all Python 3.5 tests:
  <<: *run_tox_tests
  image: python:3.5
  variables:
    PYTHON: "3.5"

run all Python 3.6 tests:
  <<: *run_tox_tests
  image: python:3.6
  variables:
    PYTHON: "3.6"

run all Python 3.7 tests:
  <<: *run_tox_tests
  image: python:3.7
  variables:
    PYTHON: "3.7"


run static checks:
  <<: *run_tox_staticcheck
  only:
    - master
    - merge_requests
  allow_failure: true


build source distribution:
  image: python:3.6-alpine
  stage: build
  script:
    - rm -f dist/*
    - python setup.py sdist
    - PROJECT_NAME=xoutil python3 setup.py sdist
  artifacts:
    paths:
      - dist/
  only:
    - tags


build binary distribution:
  image: python:3.6-alpine
  stage: build
  script:
    - pip install wheel
    - python3 setup.py bdist_wheel
    - PROJECT_NAME=xoutil python3 setup.py bdist_wheel
  artifacts:
    expire_in: 4 hours
    paths:
      - dist/
  only:
    - tags

check signature of tag:
  image: alpine
  stage: check
  script:
    - apk add git gnupg
    - gpg --recv-key $GNUPG_KEY
    - git verify-tag $CI_COMMIT_REF_NAME
  only:
    - tags


publish_locally:
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - ssh-keyscan -H gestion.lahavane.com >> ~/.ssh/known_hosts
    - ssh manu@gestion.lahavane.com "mkdir -p Repos/xoutil"
    - scp dist/xoutil* manu@gestion.lahavane.com:Repos/xoutil/
    - ssh manu@gestion.lahavane.com "mkdir -p Repos/xotl.tools"
    - scp dist/xotl* manu@gestion.lahavane.com:Repos/xotl.tools/
  tags:
    - repo.lahavane.com
  only:
    - tags
  dependencies:
    - check signature of tag
    - build source distribution
    - build binary distribution
  environment:
    name: repo.lahavane.com
    url: http://repo.lahavane.com/pypi/$CI_PROJECT_NAME

publish in pypi:
  image: python:3.6-alpine
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - pip install twine
    - twine upload --skip-existing -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
  only:
    - tags
  dependencies:
    - check signature of tag
    - build source distribution
    - build binary distribution
  environment:
    name: pypi
    url: https://pypi.org/project/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME


build documentation:
  image: python:3.6
  stage: build
  cache:
    key: docs-${CI_COMMIT_REF_SLUG}
    paths:
      - builds/doctrees
  script:
    - pip install sphinx sphinx-rtd-theme
    - pip install -e .
    - make -C docs/ html
    - cd docs/build/html
    - tar -cjf ../../../$CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 ./
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    expire_in: 4 days
  only:
    - tags
    - /^releases-/
    - master
    - merge_requests

publish in our rtd:
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - scp $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 rtd@docs.lahavane.com:.
    - ssh-keyscan -H docs.lahavane.com >> ~/.ssh/known_hosts
    - ssh rtd@docs.lahavane.com mkdir -p $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com tar -xf $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 -C $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com "rm -r /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME; ln -sr /var/www/html/$CI_PROJECT_NAME/.$CI_COMMIT_SHA /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME"
    - ssh rtd@docs.lahavane.com rm $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    - ssh rtd@docs.lahavane.com "cd /var/www/html/$CI_PROJECT_NAME; ls -al | grep -oE '\.([0-9]|[a-z])*$' | sort | uniq -c | grep '1 ' | grep -oE '\.([0-9]|[a-z])*$' | xargs rm -rf"
  tags:
    - rtd@docs.lahavane.com
  dependencies:
    - build documentation
  environment:
    name: docs.lahavane.com
    url: http://docs.lahavane.com/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
  only:
    - tags
    - /^releases-/
    - master
    - merge_requests
