---
stages:
  - test
  - check
  - build
  - publish

lint:
  image: python:3.6
  script:
    - pip install merchise.lint==0.11
    - merchise_lint3
  stage: test
  only:
    - merge_requests

check with mypy:
  image: python:3.6
  stage: test
  cache:
    key: mypy-${CI_COMMIT_REF_SLUG}
    paths:
      - .tox/3.6-staticcheck/
      - .mypy_cache/
  script:
    - pip install tox
    - tox -e3.6-staticcheck
  only:
    - merge_requests
  allow_failure: true

.run_tests: &run_tests
  stage: test
  script:
    - pip install tox
    - tox -esystem-unit,$PYTHON-greenlets
  only:
    - merge_requests


run all Python 3.4 tests:
  <<: *run_tests
  image: python:3.4
  variables:
    PYTHON: "3.4"


run all Python 3.5 tests:
  <<: *run_tests
  image: python:3.5
  variables:
    PYTHON: "3.5"

run all Python 3.6 tests:
  <<: *run_tests
  image: python:3.6
  variables:
    PYTHON: "3.6"

run all Python 3.7 tests:
  <<: *run_tests
  image: python:3.7
  variables:
    PYTHON: "3.7"


build source distribution:
  image: python:3.6
  stage: build
  script:
    - rm -f dist/*
    - python3 setup.py sdist
    - PROJECT_NAME=xoutil python3 setup.py sdist
  artifacts:
    expire_in: 4 hours
    paths:
      - dist/
  only:
    - tags
    - master

build binary distribution:
  image: python:3.6
  stage: build
  script:
    - pip install wheel
    - rm -f dist/*
    - python3 setup.py bdist_wheel
    - PROJECT_NAME=xoutil python3 setup.py bdist_wheel
  artifacts:
    expire_in: 4 hours
    paths:
      - dist/
  only:
    - tags
    - master

publish_locally:
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - ssh-keyscan -H gestion.lahavane.com >> ~/.ssh/known_hosts
    - ssh manu@gestion.lahavane.com "mkdir -p Repos/xoutil"
    - scp dist/xoutil* manu@gestion.lahavane.com:Repos/xoutil/
    - ssh manu@gestion.lahavane.com "mkdir -p Repos/xotl.tools"
    - scp dist/xotl* manu@gestion.lahavane.com:Repos/xotl.tools/
  tags:
    - repo.lahavane.com
  only:
    - tags
  dependencies:
    - build source distribution
    - build binary distribution
  environment:
    name: repo.lahavane.com
    url: http://repo.lahavane.com/pypi/$CI_PROJECT_NAME


publish in pypi:
  image: python:3.6
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - pip install twine
    - echo "[distutils]" > ~/.pypirc
    - echo "index-servers = " >> ~/.pypirc
    - echo "    pypi" >> ~/.pypirc
    - echo "[pypi]" >> ~/.pypirc
    - echo "username = $PYPI_USERNAME" >> ~/.pypirc
    - echo "password = $PYPI_PASSWORD" >> ~/.pypirc
    - twine upload --skip-existing dist/*
  only:
    - tags
  dependencies:
    - build source distribution
    - build binary distribution
  environment:
    name: pypi
    url: https://pypi.org/project/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME


build documentation:
  image: python:3.6
  stage: build
  cache:
    key: docs-${CI_COMMIT_REF_SLUG}
    paths:
      - builds/doctrees
  script:
    - pip install sphinx sphinx-rtd-theme
    - pip install -e .
    - make -C docs/ html
    - cd docs/build/html
    - tar -cjf ../../../$CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 ./
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    expire_in: 4 days
  only:
    - tags
    - /^releases-/
    - master
    - merge_requests

publish in our rtd:
  variables:
    GIT_STRATEGY: none
  stage: publish
  script:
    - scp $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 rtd@docs.lahavane.com:.
    - ssh-keyscan -H docs.lahavane.com >> ~/.ssh/known_hosts
    - ssh rtd@docs.lahavane.com mkdir -p $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com tar -xf $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2 -C $CI_PROJECT_NAME/.$CI_COMMIT_SHA
    - ssh rtd@docs.lahavane.com "rm -r /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME; ln -sr /var/www/html/$CI_PROJECT_NAME/.$CI_COMMIT_SHA /var/www/html/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME"
    - ssh rtd@docs.lahavane.com rm $CI_PROJECT_NAME-$CI_COMMIT_SHA.tar.bz2
    - ssh rtd@docs.lahavane.com "cd /var/www/html/$CI_PROJECT_NAME; ls -al | grep -oE '\.([0-9]|[a-z])*$' | sort | uniq -c | grep '1 ' | grep -oE '\.([0-9]|[a-z])*$' | xargs rm -rf"
  tags:
    - rtd@docs.lahavane.com
  dependencies:
    - build documentation
  environment:
    name: docs.lahavane.com
    url: http://docs.lahavane.com/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
  only:
    - tags
    - /^releases-/
    - master
    - merge_requests
