---
variables:
  PROJECT_NAME: xoutil

stages:
  - test
  - check
  - build
  - publish
  - clean

run all tests:
  stage: test
  script: tox -e2.7-unit,3.5-unit,2.7-greenlets
  tags:
    - python
    - virtualenv
    - tox

check signature of tag:
  stage: check
  script:
    - git verify-tag $CI_COMMIT_REF_NAME
  tags:
    - git
    - gpg
  only:
    - tags

build source distribution:
  stage: build
  script:
    - rm -f dist/*
    - python setup.py sdist
  tags:
    - python
  artifacts:
    paths:
      - dist/
  only:
    - tags

build binary distribution:
  stage: build
  script:
    - rm -f dist/*
    - python setup.py bdist_wheel
  tags:
    - wheel
  artifacts:
    paths:
      - dist/
  only:
    - tags

publish_locally:
  stage: publish
  script:
    - ssh manu@gestion.lahavane.com "mkdir -p Repos/$PROJECT_NAME"
    - scp dist/* manu@gestion.lahavane.com:Repos/$PROJECT_NAME/
  tags:
    - repo.lahavane.com
  only:
    - tags
  dependencies:
    - check signature of tag
    - build source distribution
    - build binary distribution


publish_pypi:
  stage: publish
  script:
    - twine upload dist/*
  tags:
    - twine
  only:
    - tags
  dependencies:
    - check signature of tag
    - build source distribution
    - build binary distribution
  environment:
    name: pypi
    url: https://pypi.python.org/pypi/$PROJECT_NAME


clean_build:
  stage: clean
  script:
    - rm -f dist/*
  tags:
    - python
  when: always
  allow_failure: true
  dependencies:
    - build source distribution
    - build binary distribution


build documentation:
  stage: build
  script:
    - virtualenv /tmp/venv-$CI_COMMIT_SHA
    - source /tmp/venv-$CI_COMMIT_SHA/bin/activate
    - pip install -e .
    - pip install sphinx sphinx_rtd_theme
    - make -C docs html
    - deactivate
    - rm -rf /tmp/venv-$CI_COMMIT_SHA
  artifacts:
    paths:
      - docs/build/html
  tags:
    - python
    - virtualenv


upload documentation to PyPI:
  stage: publish
  script:
    - python setup.py upload_docs --upload-dir docs/build/html
  tags:
    - twine
  dependencies:
    - check signature of tag
    - build documentation
  only:
    - tags
